[package]
name = "tic-tac-toe-rust"
version = "0.1.0"
edition = "2021"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false

[dependencies]

[[bin]]
name = "tic-tac-toe-rust"
path = "main.rs"
